### ISSUE TITLE
Hubot service restarting

### ISSUE THREAD

**Issue by marksmall** [edina/edina-hubot#14]
The Hubot service is being restarted for some reason, see the log stacktrace below. I'm not sure what is in the stacktrace is all relevant but it does indicate that the service is being restarted, while the current one is up and running, for some reason, this is why we get the **EADDRINUSE** statement. I have a feeling this is why the **update** command is not working, we set it on process 1, a new process is created when the new hubot is started, overwriting the PID of the previous process (which is still alive). This new process takes over, but has no update in it's **Brain**. Figuring out why the service is restarting and preventing it from happening is the solution to this problem I think.

```
Deferred@0.1.1 node_modules/hubot-jabbr/node_modules/njabbr/node_modules/Deferred -> node_modules/Deferred
eventsource@0.2.1 node_modules/hubot-jabbr/node_modules/njabbr/node_modules/eventsource -> node_modules/eventsource
request@2.79.0 node_modules/hubot-jabbr/node_modules/njabbr/node_modules/request -> node_modules/request
[Wed Nov 30 2016 09:21:08 GMT+0000 (GMT)] ERROR Error: listen EADDRINUSE 0.0.0.0:8080
  at Object.exports._errnoException (util.js:1026:11)
  at exports._exceptionWithHostPort (util.js:1049:20)
  at Server._listen2 (net.js:1257:14)
  at listen (net.js:1293:10)
  at net.js:1403:9
  at _combinedTickCallback (internal/process/next_tick.js:77:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Module.runMain (module.js:606:11)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

[Wed Nov 30 2016 09:21:09 GMT+0000 (GMT)] INFO Logged in as gort of teamedina
[Wed Nov 30 2016 09:21:09 GMT+0000 (GMT)] INFO Slack client now connected
info: message received on reconnect with no registered callback:
[object Object]
[Wed Nov 30 2016 09:21:10 GMT+0000 (GMT)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)`
[Wed Nov 30 2016 09:21:10 GMT+0000 (GMT)] INFO hubot-redis-brain: Using default redis on localhost:6379
```

**Comment by robertvilla** [comment]
My suspicion is that the above error was due to multiple instances of hubot being started up, due to a problem with the init.d/hubot script. While hubot would start up fine manually when puppet reprovisioned the machine a second hubot instance would sometimes be started.

Some changes have been made to this script to get it to work more reliably: a lockfile is created on start and removed on stop to match redhat standards; the line used to retrieve the hubot PID has been altered to match both node and hubot; and a longer delay has been added (the previous 3 seconds delay would start gort ok but the subsequent line which retrieves the PID would fail).
